import type { Product } from "./ProductCard";

const dummyProducts: Product[] = [
  {
    id: "1",
    name: "Apple iMac 27\" 1TB HDD Retina 5K Display M3 Max",
    price: 1699,
    image: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/imac-front.svg",
    imageDark: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/imac-front-dark.svg",
    discount: "Up to 35% off",
    rating: 5.0,
    reviews: 455,
  },
  {
    id: "2",
    name: "Apple iPhone 15 Pro Max 256GB Blue Titanium",
    price: 1199,
    image: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/iphone-light.svg",
    imageDark: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/iphone-dark.svg",
    discount: "Up to 15% off",
    rating: 4.9,
    reviews: 1233,
  },
  {
    id: "3",
    name: "iPad Pro 13-Inch (M4): XDR Display, 512GB",
    price: 799,
    image: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/ipad-light.svg",
    imageDark: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/ipad-dark.svg",
    discount: "Up to 35% off",
    rating: 4.9,
    reviews: 879,
  },
  {
    id: "4",
    name: "PlayStation®5 Console – 1TB, PRO Controller",
    price: 499,
    image: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/ps5-light.svg",
    imageDark: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/ps5-dark.svg",
    discount: "Up to 10% off",
    rating: 4.8,
    reviews: 2957,
  },
  {
    id: "5",
    name: "Microsoft Xbox Series X 1TB Gaming Console",
    price: 499,
    image: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/xbox-light.svg",
    imageDark: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/xbox-dark.svg",
    discount: "Up to 10% off",
    rating: 4.8,
    reviews: 4263,
  },
  {
    id: "6",
    name: "Apple MacBook PRO Laptop with M2 chip",
    price: 2599,
    image: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/macbook-pro-light.svg",
    imageDark: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/macbook-pro-dark.svg",
    discount: "Up to 5% off",
    rating: 4.9,
    reviews: 1076,
  },
  {
    id: "7",
    name: "Apple Watch SE [GPS 40mm], Smartwatch",
    price: 699,
    image: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/apple-watch-light.svg",
    imageDark: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/apple-watch-dark.svg",
    discount: "Up to 20% off",
    rating: 4.7,
    reviews: 387,
  },
  {
    id: "8",
    name: "Microsoft Surface Pro, Copilot+ PC, 13 Inch",
    price: 899,
    image: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/ipad-keyboard.svg",
    imageDark: "https://flowbite.s3.amazonaws.com/blocks/e-commerce/ipad-keyboard-dark.svg",
    discount: "Up to 35% off",
    rating: 4.9,
    reviews: 4775,
  },
];

export default dummyProducts; 